# -*- mode: yaml; coding: utf-8 -*-
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      all:
        dependency-type: production
