#!/bin/bash

echo "Running Flake8 Test"

flake8 . --select=E9,F63,F7,F82 --show-source --statistics

if [ $? -eq 0 ]; then 
    echo "flake 8 success"
    
    # pytest cmethods/tests/testing.py

    # if [ $? -eq 0 ]; then 
    #     echo "pytest success"
        exit 0
    # else 
    #     exit 1
    # fi
else
    exit 1
fi

