# -*- mode: yaml; coding: utf-8 -*-
#
# Copyright (C) 2023 Benjamin Thomas Schwertfeger
# All rights reserved.
# https://github.com/btschwertfeger
#
# Template workflow to run the unit tests of the package and upload the
# coverage report of the ubuntu-latest/3.11 matrix cell to Codecov.
#

name: Test Spot

on:
  workflow_call:
    inputs:
      os:
        type: string
        required: true
      python-version:
        type: string
        required: true
    secrets:
      CODECOV_TOKEN:
        required: false

permissions: read-all

jobs:
  Test:
    name: Test ${{ inputs.os }} ${{ inputs.python-version }}
    runs-on: ${{ inputs.os }}
    env:
      OS: ${{ inputs.os }}
      PYTHON: ${{ inputs.python-version }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          disable-sudo: true
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install dependencies
        run: python -m pip install --user --upgrade pip

      - name: Install package
        run: python -m pip install --user . -r requirements-dev.txt

      - name: Run unit tests
        run: pytest -vv --retries 1 -n auto --cov --cov-report=xml tests

      - name: Upload coverage to Codecov
        if: |
          inputs.os == 'ubuntu-latest'
          && inputs.python-version == '3.11'
          && github.actor == 'btschwertfeger'
          && (github.event_name == 'push' || github.event_name == 'release')
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          flags: unittests
          name: codecov-umbrella
          verbose: true
